import { randomUUID } from 'node:crypto';
import type { Logger } from 'pino';
import type { TaskBlock, Task, GameStateSnapshot } from '@asva/shared-types';

/**
 * TaskExpander
 * 
 * L3 (Tactical Layer) utility responsible for translating abstract `TaskBlock`s
 * (generated by the L4 Strategic Layer) into concrete, executable `Task`s for
 * the L2 ActionDispatcher.
 * 
 * For example, a single "WATER_CROPS" TaskBlock is expanded into N individual
 * "WATER_CROP" Tasks by inspecting the current GameState to find all unwatered crops.
 */
export class TaskExpander {
  constructor(private readonly logger: Logger) {}

  /**
   * Translates a single semantic TaskBlock into an array of concrete Tasks.
   */
  public expand(block: TaskBlock, state: GameStateSnapshot): Task[] {
    this.logger.debug({ activity: block.activity }, 'TaskExpander: expanding block');

    switch (block.activity) {
      case 'WATER_CROPS':
        return this.expandWaterCrops(block, state);
      case 'HARVEST_CROPS':
        return this.expandHarvestCrops(block, state);
      case 'SLEEP':
        return [this.createBaseTask('SLEEP', block, { skipPath: true })];
      default:
        this.logger.warn(
          { activity: block.activity },
          'TaskExpander: unhandled activity type — returning empty task list'
        );
        return [];
    }
  }

  private expandWaterCrops(block: TaskBlock, state: GameStateSnapshot): Task[] {
    const unwateredCropTiles = state.farm.tiles.filter(
      (tile) => tile.cropId !== null && !tile.watered
    );

    return unwateredCropTiles.map((tile) =>
      this.createBaseTask('WATER_CROP', block, {
        tileX: tile.x,
        tileY: tile.y,
        map: 'Farm', // Hardcoded to farm for Phase 2/3, could match block.location
      })
    );
  }

  private expandHarvestCrops(block: TaskBlock, state: GameStateSnapshot): Task[] {
    const harvestableCropTiles = state.farm.tiles.filter(
      (tile) => tile.cropId !== null && tile.daysToHarvest !== null && tile.daysToHarvest <= 0
    );

    return harvestableCropTiles.map((tile) =>
      this.createBaseTask('HARVEST_CROP', block, {
        tileX: tile.x,
        tileY: tile.y,
        map: 'Farm',
      })
    );
  }

  /**
   * Helper to stamp out boilerplate Task fields.
   */
  private createBaseTask(
    type: Task['type'],
    block: TaskBlock,
    parameters: Record<string, unknown> = {}
  ): Task {
    return {
      id: randomUUID(),
      type,
      priority: block.priority,
      estimatedDurationTicks: block.estimatedDurationTicks, // L4 estimate
      energyCost: block.energyCost,
      prerequisites: [],
      parameters,
      status: 'pending',
      attemptCount: 0,
      createdAt: new Date().toISOString(),
    };
  }
}
